# Generated by Django 4.2.18 on 2025-04-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentifications", "0004_alter_customuser_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="account_ready",
            field=models.BooleanField(default=False),
        ),
    ]
