# Generated by Django 4.2.18 on 2025-06-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentifications", "0006_customuser_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="withdraw_code",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
